# POST http://localhost:3000/signin
# Content-Type: application/json

# {
    
#     "email":"nimna@yahoo.com",
#     "password":"Nimna1234"
# }

# GET http://localhost:3000/get-upload-url


# POST http://localhost:3000/create-blog
# Content-Type: application/json

# {
#     "blog-name":"this is a test blog"
# }

 #after get the access token :eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY2NTk2YTU2OTEzZWVkMjljZTgzNjFkNyIsImlhdCI6MTcxODQ2NTEzOX0.y8nIsISE1tpkqHRh6IkTC7J6W7hqbal78vM4T2GRP9E
# POST http://localhost:3000/create-blog
# Content-Type: application/json
# Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY2NTk2YTU2OTEzZWVkMjljZTgzNjFkNyIsImlhdCI6MTcxODcwMTk2MH0.WiIIbUVfzblVgnvb5ecnllKjyNAjJBwKaJ20cVB-BaM

# {
#     "title": "test title isuru sandaruwn",
#     "banner": "https://dfsdgsggsgs.com",
#     "des": "this dfsdgsfgfsgdgf gfg",
#     "content": { "blocks": [1, 2] },
#     "tags": ["tag1", "tag2"]
# }



# GET  http://localhost:3000/latest-blogs

# GET  http://localhost:3000/trending-blogs


# POST  http://localhost:3000/search-blogs
# Content-Type: application/json

# {
#     "tag":"vevo"
# }



# POST  http://localhost:3000/search-users
# Content-Type: application/json

# {
#     "query":"isuru"
# }

# POST  http://localhost:3000/get-profile
# Content-Type: application/json

# {
#      "username":"isurusandaruwan0601"
# }


# POST  http://localhost:3000/get-blog
# Content-Type: application/json

# {
#      "blog_id":"java-Binaray-SearchPkMurcr7sF5JpBCpoxSUl"
# }


# POST http://localhost:3000/signin
# Content-Type: application/json

# {
    
#     "email":"isurusandaruwan0601@gmail.com",
#     "password":"Isuru123"
# }

POST http://localhost:3000/change-password
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY2YTljNDA3MWM5Yjk2OTQxNzU3NjY5NyIsImlhdCI6MTcyMzMxMTY2NX0.5kcaz7O7waLVOSGvGMEfnYPgyOrc7o_dkDc6NoXUxLk

{
     "currentPassword":"Isuru123",
     "newPassword":"Isuru321"
}